services:
    pa.admin.pa_complaint:
        class: PaBundle\Admin\PaComplaintAdmin
        arguments: [~, PaBundle\Entity\PaComplaint, PaBundle:PaComplaintAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaComplaint }

    pa.admin.pa_vote_cast:
        class: PaBundle\Admin\PaVoteCastAdmin
        arguments: [~, PaBundle\Entity\PaVoteCast, PaBundle:PaVoteCastAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaVoteCast }

    pa.admin.pa_party:
        class: PaBundle\Admin\PaPartyAdmin
        arguments: [~, PaBundle\Entity\PaParty, PaBundle:PaPartyAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaParty }

    pa.admin.pa_candidate:
        class: PaBundle\Admin\PaCandidateAdmin
        arguments: [~, PaBundle\Entity\PaCandidate, PaBundle:PaCandidateAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaCandidate }

    pa.admin.pa_foot_print:
        class: PaBundle\Admin\PaFootPrintAdmin
        arguments: [~, PaBundle\Entity\PaFootPrint, PaBundle:PaFootPrintAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaFootPrint }

    pa.admin.pa_notification:
        class: PaBundle\Admin\PaNotificationAdmin
        arguments: [~, PaBundle\Entity\PaNotification, PaBundle:PaNotificationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaNotification }

    pa.admin.pa_pink_sheet:
        class: PaBundle\Admin\PaPinkSheetAdmin
        arguments: [~, PaBundle\Entity\PaPinkSheet, PaBundle:PaPinkSheetAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Parliamentary, label: PaPinkSheet }
